spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronosdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true
    swagger-ui:
      path: /swagger-ui.html
  show-actuator: true

jwt:
  secret: "MyVeryLongSecretKeyThatIsAtLeast64CharactersLongAndSecureForHS512!"
  expiration: 3600000
